# all the keys have to be symbols or ActiveLDAP::Base.connect() gets mad

development:
  host: ldap.slackworks.com
  base: dc=slackworks,dc=com 
  allow_anonymous: false
  bind_dn: uid=root,dc=slackworks,dc=com
  password: menthol
  method: ssl
  port: 636
  
test:
  host: ldap.slackworks.com
  base: dc=slackworks,dc=com
  allow_anonymous: false
  bind_dn: uid=root,dc=slackworks,dc=com
  password: menthol
  method: ssl
  port: 636

production:
  host: ldap.slackworks.com
  base: dc=slackworks,dc=com 
  allow_anonymous: false
  bind_dn: uid=root,dc=slackworks,dc=com
  password: menthol
  method: ssl
  port: 636
