# all the keys have to be symbols or ActiveLDAP::Base.connect() gets mad

development:
  !ruby/symbol host: ldap.slackworks.com
  !ruby/symbol base: dc=slackworks,dc=com 
  !ruby/symbol allow_anonymous: true
  
test:
  !ruby/symbol host: ldap.slackworks.com
  !ruby/symbol base: dc=slackworks,dc=com
  !ruby/symbol allow_anonymous: true

production:
  !ruby/symbol host: ldap.slackworks.com
  !ruby/symbol base: dc=slackworks,dc=com 
  !ruby/symbol allow_anonymous: true
  